apiVersion: apps/v1
kind: Deployment
metadata:
  name: bonfim
  namespace: bonfim
spec:
  replicas: 5
  selector:
    matchLabels:
      app: bonfim
  template:
    metadata:
      labels:
        app: bonfim
    spec:
      containers:
        - name: bonfim
          image: nginx:alpine
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: bonfim
  namespace: bonfim
spec:
  selector:
    app: bonfim
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
